// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Button: typeof import('./components/Button.vue')['default']
    Checkbox: typeof import('./components/Checkbox.vue')['default']
    copy: typeof import('./components/StatusTag copy.vue')['default']
    Dropdown: typeof import('./components/Dropdown.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Input: typeof import('./components/Input.vue')['default']
    MenuItem: typeof import('./components/MenuItem.vue')['default']
    ProductItem: typeof import('./components/ProductItem.vue')['default']
    ProductsHeader: typeof import('./components/ProductsHeader.vue')['default']
    Select: typeof import('./components/Select.vue')['default']
    StatusTag: typeof import('./components/StatusTag.vue')['default']
  }
}
