// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Button: typeof import('./components/Button.vue')['default']
    Checkbox: typeof import('./components/Checkbox.vue')['default']
    CheckboxGroup: typeof import('./components/CheckboxGroup.vue')['default']
    copy: typeof import('./components/Modal copy.vue')['default']
    CreateProductForm: typeof import('./components/CreateProductForm.vue')['default']
    Dropdown: typeof import('./components/Dropdown.vue')['default']
    Filter: typeof import('./components/Filter.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Input: typeof import('./components/Input.vue')['default']
    MenuItem: typeof import('./components/MenuItem.vue')['default']
    Modal: typeof import('./components/Modal.vue')['default']
    ProductFilters: typeof import('./components/ProductFilters.vue')['default']
    ProductItem: typeof import('./components/ProductItem.vue')['default']
    ProductsHeader: typeof import('./components/ProductsHeader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('./components/Select.vue')['default']
    StatusTag: typeof import('./components/StatusTag.vue')['default']
    TextArea: typeof import('./components/TextArea.vue')['default']
  }
}
